- name: ContainerB
  hosts: localhost
  become: yes
  tasks:
    - name: Docker install 
      yum:
        name: docker-ce
        state: present
        
    - name: start docker
      service: 
        state: started
        enabled: yes
        
    - name: pull image
      community.docker.docker_image: 
        image: ubuntu:latest
        state: present

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerB
        image: ubuntu:latest
        exposed_ports:
          - "22"
        published_ports:
          - "22:22" 
          
    - name: genera Keys
      community.crypto.openssh_keypair:
      #  path: /tmp/id_ssh_rsa
        path: /home/giosue/.ssh/id_rsa.pub
 
    - name: Set key nella macchina host
      ansible.posix.authorized_key:
        user: giosue
        state: present
        key: "{{ lookup('file', '/home/giosue/.ssh/id_rsa.pub') }}"
        
    - name: Install sudo and SSH server in container
      community.docker.docker_container_exec:
        container: ContainerB
        command: yum install -y sudo openssh-server
        
    - name: crea e aggiungi user al sudo group
      community.docker.docker_container_exec:
        container: ContainerB
        command: > 
          sh "useradd -m -s /bin/bash giosue && usermod -aG sudo giosue"

    - name: Copy SSH public key to container
      community.docker.docker_container_exec:
        container: ContainerB
        command: >
          sh  "mkdir -p /home/giosue/.ssh &&
               echo '{{ lookup('file', '/home/giosue/.ssh/id_rsa.pub') }}' >> /home/giosue/.ssh/authorized_keys &&
               chmod 600 /home/giosue/.ssh/authorized_keys"

    - name: Start SSH service in container
      community.docker.docker_container_exec:
        container: ContainerB
        command: systemctl start sshd

    - name: Enable SSH service in container
      community.docker.docker_container_exec:
        container: ContainerB
        command: systemctl enable sshd
