- name: ContainerStep5
  hosts: localhost
  become : yes
  tasks:
  
    - name: Start Docker service
      ansible.builtin.command: "open -a Docker"
        
    - name: pull image
      community.docker.docker_image:
        name: jenkins/jenkins:lts
        source: pull

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerStep5
        image: jenkins/jenkins:lts
        exposed_ports:
          - "22"
        published_ports:
          - "2222:22" 
        ports:
          - "8080:8080"  
