- name: configurare un Docker Registry
  hosts: localhost
  become: true
  
  tasks:  
    - name: Start Docker service
      ansible.builtin.command: "open -a Docker"
     
    - name: pull image
      community.docker.docker_image:
        name: registry:latest
        state: present

    - name: configura registry Docker
      docker_container: 
        name: Registry
        image: registry:latest
        state: started
        exposed_ports:
          - "5000"
        published_ports:
          - "5000:5000"
