- name: ContainerA
  hosts: localhost
  become: yes
  tasks:

    - name: Build image
      docker_image:
        path: ./Step2
        name: image1
        dockerfile: Dockerfile2_1
        state: present

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerA
        image: image1
        exposed_ports:
          - "22"
        published_ports:
          - "22:22" 

