- name: ContainerA
  hosts: localhost
  become: yes
  tasks:

    - name: Build image
      docker_image:
        name: image1
        tag: latest
        build:
          path: ./Step2
          dockerfile: Dockerfile2_1

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerA
        image: image1
        exposed_ports:
          - "22"
        published_ports:
          - "22:22" 

