- name: ContainerB
  hosts: localhost
  become: yes
  tasks:

    - name: Build image
      docker_image:
        path: ./Dockerfile2_2
        name: Image2
        source: build

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerB
        image: Image2
        exposed_ports:
          - "22"
        published_ports:
          - "22:22" 

