- name: ContainerB
  hosts: localhost
  become: yes
  tasks:

    - name: Build image
      docker_image:
        name: image2
        source: build
        build:
          path: ./Dockerfile2_2
          dockerfile: Dockerfile2_2

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerB
        image: Image2
        exposed_ports:
          - "22"
        published_ports:
          - "22:22" 

