- name: ContainerA
  hosts: localhost
  become: yes
  tasks:

    - name: Build image
      docker_image:
        path: .
        name: Image1
        source: build
        dockerfile: Dockerfile2_1

    - name: crea container in ascolto su porta 22
      docker_container:
        name: ContainerA
        image: Image1
        exposed_ports:
          - "22"
        published_ports:
          - "22:22" 

